name: shellcheck
run-name: shellcheck for login.sh, triggered by ${{ github.actor }}
on: [push, pull_request, workflow_dispatch]
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install Dependencies
        run: sudo apt install -y shellcheck
      - name: Run .ci/shellcheck.sh
        run: .ci/shellcheck.sh

